#!/bin/sh

RAW="`echo $* | sed -e's/^0x//'`"
DECODED="`echo $RAW | mndecode | bytes2hex`"

curl -s "http://keys.nayr.net:11371/pks/lookup?search=0x$RAW&op=index&exact=on&options=mr" | grep uid | sed -e's/^.*:.*)\? <\([^>]*\)>.*$/\1/g'
curl -s "http://keys.nayr.net:11371/pks/lookup?search=0x$DECODED&op=index&exact=on&options=mr" | grep uid | sed -e's/^.*:.*)\? <\([^>]*\)>.*$/\1/g'
